### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by turutupa** [spaceduck-theme/nvim#8]
Is this repo still being maintained? Or is it just not working for me? 

I installed `spaceduck` in both my linux (alacritty and xfce4-term) and macbook pro (iterm2) machines and the theme looks nothing like the screenshots. 

I installed the theme for vscode and that one looks correct, just like the pictures. But the nvim theme is completely different.

**Comment by pineapplegiant** [comment]
It has not been maintained, but I do want to update it eventually. I've been wanting to re-work the colors some more but haven't gotten around to it so that's why you see the discrepancy. 

Do use the older Vim one as this hasn't been fleshed out yet

**Comment by turutupa** [comment]
Got it. Thanks for your quick response! Looking forward to an update, colors in vscode look absolutely gorgeous! ;)

**Comment by Nargonath** [comment]
I ported the old vim to the Lua for nvim and this is what you find in this repo. I use it everyday on my end and I have no problem with it. The first thing that comes to mind is which version of NeoVim are you using @turutupa? I'd have to check the code again but I might have used features for highlighting group specific to NeoVim v0.8+ and forgot to write it in the README.

**Comment by turutupa** [comment]
These is taken from my linux machine (again, it looked the same both in my mac machine and linux machine but if you want I can take screenshot on my mac as well) and neovim version also down below. 

Let me know if you need any more details. Also, I'm using [lunarvim](https://www.lunarvim.org/). 

```
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```

react
![image](https://github.com/spaceduck-theme/nvim/assets/44581951/a7d2d485-df3f-4832-a9c8-53cbcbaa6833)

go
![image](https://github.com/spaceduck-theme/nvim/assets/44581951/eba28671-db49-4766-87c7-c0003ace0b12)

**Comment by Nargonath** [comment]
Alright, thanks for all the information @turutupa. From what you originally wrote I thought you didn't have any colours displayed or something like that. From what I can see, it's definitely the current state of the theme. I work on the same thing as you do. I think the problem here is as Treesitter evolved new highlighting groups where created giving you more precise control over the different part of the code. Sadly none of us took the time yet to handle these new groups and they just inherit from other less specific groups that we already defined which might not be the best.

If you feel up to it, I think what would be of help is for you to open new tickets on the repo and showing/listing what you'd like the final result to be for the languages you're interested in. I'm not promising we'll tackle it soon or that we'll abide 100% to your suggestion but at least it would give us a base to start from. If you don't feel up to it, that's ok to and thank you already to have taken the time to raise us your issue. 😃

**Comment by turutupa** [comment]
Sounds like a great new challenge! Right now I'm starting a new job so I don't have as much time but I'll keep it in mind. Thank you so much for the proposition :)

**Comment by Nargonath** [comment]
Sure you're welcome @turutupa. Well done for your new position. Good luck. 😉
